#!/usr/bin/env bash
# Builds the tool-specific agent files from each agent's charter.
#
# Why this exists: Claude Code and Kiro both want a markdown file with YAML
# frontmatter on top and the system prompt as the body. The frontmatter differs
# per tool. The prompt doesn't. So each agent keeps ONE charter.md as the source
# of truth, a tiny frontmatter file per tool, and this script glues them
# together into dist/. Edit the charter, run this, commit the output.
#
# The body also gets the two shared contracts prepended, so an installed agent
# is self-contained. Once it's copied into someone else's ~/.claude/agents/ it
# can't reach back into this repo for shared/output-format.md.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0
for agent_dir in agents/*/; do
  agent_dir="${agent_dir%/}"
  agent="$(basename "$agent_dir")"
  charter="$agent_dir/charter.md"
  [ -f "$charter" ] || { echo "skip $agent: no charter.md"; continue; }

  for adapter in "$agent_dir"/adapters/*.yaml; do
    [ -f "$adapter" ] || continue
    tool="$(basename "$adapter" .yaml)"
    out_dir="$agent_dir/dist/$tool"
    out="$out_dir/$agent.md"
    mkdir -p "$out_dir"
    {
      cat "$adapter"
      echo
      echo "<!-- Generated by scripts/build.sh from charter.md and shared/. Do not edit this file. Edit the charter. -->"
      echo
      cat shared/review-contract.md
      echo
      echo "---"
      echo
      cat shared/output-format.md
      echo
      echo "---"
      echo
      cat "$charter"
    } > "$out.tmp"
    if [ -f "$out" ] && cmp -s "$out.tmp" "$out"; then
      rm "$out.tmp"; echo "unchanged  $out"
    else
      mv "$out.tmp" "$out"; echo "wrote      $out"
    fi
  done
done

# --check mode: fail if anything would change. CI uses this so a stale dist/
# can't get merged.
if [ "${1:-}" = "--check" ]; then
  if ! git diff --quiet -- agents/*/dist/; then
    echo
    echo "dist/ is out of date. Run scripts/build.sh and commit the result."
    git --no-pager diff --stat -- agents/*/dist/
    fail=1
  fi
fi
exit $fail
